### ISSUE TITLE
Better page titles

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#146]
A lot of pages don't have a proper <title> tag set in the controllers. When no $title is defined, the global app template just use "agorakit" (or a defined app name). This is not very useful when you have tons of tabs open. For example discussions should show the discussion name, when editing a discussion the title could be "Editing [discussion name]"), same for overviews like calendars.
 
To set the title tag, one need to set the $title to be picked up by the view.
add a with->('title', $title) in controllers methods as much as possible and  it will be used in the app.blade view

**Comment by James-N-M** [comment]
Ill pick this one up !

**Comment by philippejadin** [comment]
great ! and thank you by the way

**Comment by James-N-M** [comment]
Can I get some more information on this issue, I thought I understood the issue but I guess I don't

**Comment by philippejadin** [comment]
I added some more explanation. Makes sense ?
