### ISSUE TITLE
Possibility to pin files and other stuff like discussions

### ISSUE THREAD

**Issue by pgramme** [agorakit/agorakit#160]
In the Files tab, would be great to have the possibility to "pin" files. These pinned files would stay on top, whatever the display sorting chosen. Can probably be implemented as a special Tag on the file (but I'm not an expert).

[and by the way I'm a happy user at reseautransition.be: thanks a lot!]

**Comment by nleguillarme** [comment]
+1
It would be great to be able to pin a discussion at the top of the Discussions tab, for instance for welcome message for new users, etc.

**Comment by philippejadin** [comment]
ok moving this upper in the priorities :-)

**Comment by philippejadin** [comment]
also ability to pin groups

**Comment by philippejadin** [comment]
implementation plan :

add "status" field to discussions, files and groups : 

- 0 (default) : normal
- 10 : pinned
- -10 : archived

Might be used for other stuff later (custom sorting maybe).
Discussions and other items are then sorted by status desc + any other field like name or created_at.

Implemented using a trait : class hasStatus
- isPinned()
- isArchived()
- pin()
- unPin()
- archive()
- unArchive()

**Comment by boherm** [comment]
I'm on it!

**Comment by philippejadin** [comment]
@boherm great!
I'd prefer the homemade trait solution instead of using the package I mentioned (because for instance we can sort by status and have logical ordre of items in the same query), but let me know how it goes :-)

**Comment by boherm** [comment]
@philippejadin I'd prefer this solution too :)

**Comment by philippejadin** [comment]
Thanks to @boherm this is now a reality!
Files, discussions and groups can be pinned / archived by group admins.

I'll later add some unpoly spices to avoid full page reloads. Also might be nice to have a quick admin menu on discussion list (like the 3 dots we see on github + dropdown menu).

**Comment by pgramme** [comment]
Fantastic, thanks to you two !
