### ISSUE TITLE
Files with editable content

### ISSUE THREAD

**Issue by pgramme** [agorakit/agorakit#161]
Currently, "Edit"ing a file only edits its associated metadata, not the content itself. This is hard to understand for some users (I had a few questions in my group).

Quick fix: 
 - rename "Edit" to "Edit metadata" 
 - make it possible to re-upload (overwrite) the file

Better, longer fix: make editable files possible for common file types. One option would be to integrate with an Etherpad and Ethercalc instance on the same server. The workaround I have used until now is to create my files on Framapad.org/Framacalc.org and make a link rather than a file in Agora. It works perfectly but apparently it sounds complex/frightening to many users :-)

**Comment by philippejadin** [comment]
Good idea and quick fix. I'd like at some point to add real editing features. It could be using this : https://www.zoho.com/officeapi/documentation/v1/ (allow to edit normal word-processor and spreadsheet editing in the browser and upload back to the instance). I need to check the pricing...

It's unfortunate that framapad and the like do not provide a good api (afaict)

**Comment by pgramme** [comment]
Sorry for the delay, missed the notification.

Didn't know about Zoho but it seems interesting. I have already heard about the following, which may also be a comparable solution. Don't know which one is best...
https://www.collaboraoffice.com/community-en/understanding-the-differences-between-libreoffice-online-code-and-collabora-online/

But maybe a full-featured online Office editor is overkill, and it would be sufficient to have a combination of lightweight editable (like Etherpad) + fully-featured not editable (like current solution).

Is there a need for an API to Framapad and the likes? Naive suggestion:

- create hopefully unique link using a long hash, e.g. https://annuel.framapad.org/p/913027e82be0e4231b2b6b806d78d0f20c7acbf3 (or better, on a self-hosted instance of etherpad/calc)
- save this link to AgoraKit, like it is done for any other link
- when accessed by any user, open it in an iframe on the same page (if possible)

One drawback of this is that the user name is not communicated from AgoraKit to Etherpad, which will make change tracking harder.

**Comment by samuk** [comment]
Collabra office would be a possibility for this: https://www.cloudron.io/store/com.collaboraoffice.coudronapp.html

You could stick it on a cloudron instance to make the hosting simple.

**Comment by philippejadin** [comment]
I'd prefer onlyoffice, I have the feeling it's a more robust solution. The example is ugly but maybe there is a package for that : https://github.com/ONLYOFFICE/document-server-integration/tree/master/web/documentserver-example/php

**Comment by linc** [comment]
This is added to the roadmap! https://github.com/agorakit/agorakit/blob/main/ROADMAP.md
