### ISSUE TITLE
Provide global (sitewide) notification setting

### ISSUE THREAD

**Issue by nedjo** [agorakit/agorakit#183]
Similar to #80.

Currently users can select their notification preferences per group.

Users may wish to change notifications for all groups at once. For example, they may wish to put notifications on hold while they're away.

One approach to enabling this would be to have a global (sitewide) setting saved in relation to the user profile. Then for each group, a user could select either "use my global settings" or a custom one.

**Comment by nedjo** [comment]
Hmm. An advantage of a global setting is there's no requirement to set per-group. Once you've selected your global, new groups by default get it. It's a pattern used by, for example, GitLab. The pattern also supports use cases like:

* My global default is to receive daily updates.
* There are specific groups I've overridden my global setting to not receive updates.
* Temporarily, I set my global to no notifications.
* Later, I restore my global setting to daily updates, but I don't lose the fact that there are several groups I don't receive updates for.

> Seems easier for users than having to remember what their global setting is and how to change it.

This _could_ be offered in help text on the form for an individual group. "Your global setting is X. You can change it by [link]editing your user profile[/link]."

**Comment by philippejadin** [comment]
Looks good. I need to check what are the implications on the DB, since the notification queries need the interval (and the query is already complex at least for me, see https://github.com/philippejadin/agorakit/blob/master/app/Console/Commands/SendNotifications.php#L75 ). This is an area where help would be appreciated.

**Comment by nedjo** [comment]
Here are some rough and untested ideas.

Add a field `users.notification_interval`

Add a notifications select to the user profile edit form, with valid values the same as currently for `membership.notification_interval`.

To the existing notifications select for group membership at `groups/[group ID]/preferences`, add a new select value, `global`, for notifications.

In `intervalToMinutes`, add a new case, altering the value saved to `membership.notification_interval`:

 ```
    case 'global':
      $minutes = 0;
      break;
```
In `SentNotifications::getNotificationsToSend()`, alter the select to join on `users` as follows:

```sql
        select * from
        (select *, date_add(m.notified_at, m.interval, (if(m.notification_interval = 0, u.notification_interval, m.notification_interval)) minute) as notify from membership m inner join users u on m.user_id = u.id
        where (m.notification_interval > 0 or (m.notification_interval = 0 and u.notification_interval > 0))
        and m.membership >= :membership) as memberships
        where m.notify < :now or m.notify is null
```

**Comment by nedjo** [comment]
As for the accompanying migration....

At the simplest, it would simply choose a sensible default value for `users.notification_interval` and set that for all existing users.

A more nuances migration might look at existing settings for each user and set an appropriate default. For each user:

* Determine their most used value of `membership.notification_interval`.
* Set this value as their global preference (`users.notification_interval`).
* Update their `membership.notification_interval` and set it to `0` (= 'global') where this most used value was present.

**Comment by philippejadin** [comment]
Great stuff and highly detailed, next time don't hesitate to dare the pull request :-)

I'll test this asap and report here

**Comment by nedjo** [comment]
Thinking more about this...

Currently the `membership.notification_interval` field controls two questions: _whether_ a user is notified; and, if so, how often.

We have various forms of notification. There's the user profile contact form. In #80, we have a proposal to add a new user profile select for that. Users may also wish to control whether they're notified on mention. That's not yet supported. Then there's the focus of this issue: discussion notifications.

That's only so far. It's quite possible we'll come up with new notification use cases in future.

To avoid an expanding plethora of different settings, one per type of notification, we should probably at least consider the pattern of a notification _level_. A fairly fully developed example of this pattern is in Gitlab; see [relevant documentation](https://docs.gitlab.com/ee/workflow/notifications.html).

There the levels are:

>>>
* Disabled - turns off notifications
* Participating - receive notifications from related resources
* Watch - receive notifications from projects or groups user is a member of
* Global - notifications as set at the global settings
* Custom - user will receive notifications when mentioned, is participant and custom selected events
>>>

A possible approach would be:

* In this issue, rather than extending the existing `notification_interval` setting, introduce a new one, `notification_level`. Interval would then be only for how often to receive updates, not whether or for what.
* For now, support only built-in notification levels, modelled loosely on those used in Gitlab.

Initial levels could be:

* Disabled - turns off notifications
* Mention - receive notifications when you're mentioned
* Watch - receive notifications from groups you're a member of
* Global - notifications as set at the global settings

In the longer term, we could consider adding:

* Participating - receive notifications from discussions you've participated in or are mentioned in [This goes between "Mention" and "Watch", but depends on tracking participation, which is not yet implemented]
* Custom - user will receive notifications when mentioned, is participant and custom selected events
