### ISSUE TITLE
Facilitate modification/extension of functionality and ease new developer experience

### ISSUE THREAD

**Issue by nedjo** [agorakit/agorakit#187]
Agorakit has a set of features (areas of functionality), each of which has related data and UI elements.

Just what constitutes a distinct feature is debatable, but possibly something like:

* User profiles.
* Groups.
  * Group membership.
  * Discussions + comments.
  * Actions (Calendar).
  * Files.

The current architecture is fairly monolithic. Code for a particular feature is not isolated but is spread throughout the app.

For example, in `UserController::destroy()`, we have code specific to memberships, discussions, comments, actions, and files.

This works fine so long as we assume a limited set of features, all of which are used on all sites. But it presents challenges if particular developers wish to extend the platform--for example, by adding their own group-aware feature.

* It's a non-trivial task to discover all the places in the app that need to be updated/changed/extended to integrate the new functionality.
* These changes can only be made by directly editing the existing code.

An alternative would be to refactor the current code into:

* A core app (the current repo).
* Multiple new packages (Laravel packages? regular Composer packages?) that extend the core app.

Doing so would likely require an event-based approach. Returning to the example of `UserController::destroy()`, this could be refactored to dispatch an event, with the existing feature-specific code moved to event subscribers.

Refactoring in this way would be a lot of work. It's not clear the advantages justify that level of effort. But it could also open up future possibilities.

**Comment by philippejadin** [comment]
Not exactly the same kind of monolith, but I'm a fervent believer of this : https://m.signalvnoise.com/the-majestic-monolith-29166d022228

In our case, if it has no clear advantages I'd keep it as it is in the name of simplicity.

I also believe that often, everyone have almost the same needs, so providing options in the form of packages is not that useful. On the other hand when it will happen, it will be time to refactor.

At least the event subscriber system should be used. Let's draft it :-)

**Comment by nedjo** [comment]
> At least the event subscriber system should be used. Let's draft it :-)

Sounds good!

Retitling to focus on goals.
