### ISSUE TITLE
Tags : Allow group admin to define a list of tags and provide a sane default

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#221]
Tags quickly get messy if not constrained. I'd like to have a nice list of tags (like github labels) and allow group admin to change the allowed tags. This way they will be more limited. Also allow to use colours.

- [x] Allow admin to set a predefined list of tags on their group (like on github issues). (stored as an array in the group settings)

- [x] Only show those tags on user edit / filter screens

**Comment by philippejadin** [comment]
- Allow admin to set a predefined list of tags on their group (like on github issues). (stored as an array in the group settings)
- Only show those tags on user edit / filter screens

**Comment by philippejadin** [comment]
also use this for dropdowns (both filter and edit screens)
https://developer.snapappointments.com/bootstrap-select/examples/

**Comment by nedjo** [comment]
This indeed sounds like a solid plan. It balances flexibility with constraint. If tags are arbitrarily generated, they often don't serve the purpose of helping classify content.

**Comment by philippejadin** [comment]
thanks for the feedback. Also here there is a list of preset labels that could be useful (a simplified version that is)
https://github.com/jasonbellamy/git-label-packages/tree/master/packages

found here : https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63

**Comment by philippejadin** [comment]
tag ui needs rework but at least the basic features are there
