### ISSUE TITLE
Discussions : display messages in inverted chronological order

### ISSUE THREAD

**Issue by nleguillarme** [agorakit/agorakit#222]
Hi. Thank you so much for your amazing work on Agorakit. It is very useful to our association and the only tool we found that fulfill almost all our needs.

Here is a suggestion of functionality that would facilitate navigation on mobile devices : would it be possible to add a setting to display messages in inverted chronological order, starting with the most recent message and finishing with the oldest.

That may not be useful to a lot of people, and not really in accordance with classical forum rules, but if it does not represent too much work, that would be really appreciated by our members.

**Comment by philippejadin** [comment]
Are you talking about the comments attached to a discussion?
On a discussion page here for example : https://app.agorakit.org/groups/39/discussions/368 

Would the main discussion text still stays on top ?

Would it be per-user defined ?

If you could make a UI mockup (just a quick picture) this would help (or show example from other apps)

**Comment by nleguillarme** [comment]
That's it, the comments attached to a discussion in reverse order, and the main discussion can stay on top.

To give you more details, we use a discussion to register the different actions carried out on our project, the idea would be to access more quickly the latest actions so it would be nice to make them appear first.

Whether it is per-user defined or defined by the person initiating the discussion is not so important to us. I guess the easiest option to implement is the right one :)

**Comment by pgramme** [comment]
Would be nice indeed, but it still be necessary if feature request #193 is implemented? Personally I don't think so

**Comment by philippejadin** [comment]
The latest version at least scrolls to the first unread comment. I'll add folding of read comments soon. Also every 10 seconds or so, it reload the newest comments and show the number of unread comments like whatsapp. It will make the experience more real time I guess.

**Comment by nleguillarme** [comment]
Great work, thank you very much !
