### ISSUE TITLE
add reactions

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#234]
- add some package to allow one to react, at least to comments (possibly to other models later). Using this maybe : https://github.com/qirolab/laravel-reactions
- add routes to react to comments /comments/[id]/react/like /comments/[id]/unreact (or other wording ?)
- add user interface to add a reaction, first a form that is on a new page
- add user interface to show the existing reactions on each comment
- then use unpoly to make a modal to change reactions, and to update just the comment in situ.

I'd mimic github for the ui and the available reactions, I really like it. Feel free to propose other reactions.

**Comment by James-N-M** [comment]
I'll pick this up unless you think theirs a easier feature I can do like this perhaps ? #204

**Comment by philippejadin** [comment]
@James-N-M it's fine if you attack this one. Maybe we can ask @danielsum for recomendation for a +1 -1 package to add a trait to models for this purpose?

The package I linked above at least has a decent DB schema imho with room for extensions since we can basically add any kind of reactions (it's just a text field) : https://github.com/qirolab/laravel-reactions/blob/master/migrations/2018_07_10_000000_create_reactions_table.php

**Comment by James-N-M** [comment]
@danielsum Let me know what you think about it all ! :)

**Comment by philippejadin** [comment]
I updated the description with some more ideas on how to do it.

**Comment by boherm** [comment]
@philippejadin Yes why not ! But I 'm busy this month... :/

**Comment by philippejadin** [comment]
Re-activitating this one !

I'd favor using this package : https://github.com/qirolab/laravel-reactions

if no one has time to work on it, I'll do it :-)

**Comment by boherm** [comment]
Maybe I can work on it soon ! :-)

**Comment by philippejadin** [comment]
This would be cool !
I already created a reactions branch with the package installed and hopefully the correct migration (since I already had a reactions table from a previous attempt)

**Comment by philippejadin** [comment]
I'm slooowly getting there in the reactions branch. I ended up removing the package because it was counter-intuitive at least for me.

**Comment by philippejadin** [comment]
A good enough solution has been implemented.
