### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#243]
- You can read the docs here : https://agorakit.readthedocs.io/en/latest/
- The repository has a /docs directory
- Everyone is welcome to enhance the docs (written by a non native english speaker :-))

**Comment by nasanos** [comment]
Great project that I'd be glad to be a part of!

I'm submitting a pull request with some initial documentation enhancements. If they aren't in the direction you're looking for, let me know and I'll adjust. Otherwise, I'll plan on submitting some more enhancements along the same lines.

**Comment by philippejadin** [comment]
THis is great that you want to be part of the project. Welcome !

I'll review the pr soon, I'm confident it will be great since my english need a lot of cleanup.

At some point woriking in end user doc would be a cool project. let me know if you are interested

**Comment by nasanos** [comment]
I would certainly be interested in helping on that! Just keep me posted.

**Comment by philippejadin** [comment]
@nasanos the idea would be to work on end user documentation. Like creating a end user, step by step guide for group admins and group users. There is a single page currently here : https://agorakit.readthedocs.io/en/latest/usage.html (built from https://github.com/philippejadin/agorakit/blob/master/docs/usage.rst )

This page needs much more details, and screenshots. If you want to work on this, you could create an account on app.agorakit.org and create a test group there to document the process.

This would really help a lot of users, and the project itself.

**Comment by philippejadin** [comment]
doc has been moved here btw : docs.agorakit.org

It is generated form the docs folder in this repository

Help is always welcome
