### ISSUE TITLE
Add realtime commenting

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#244]
When a new comment is submited, notify other users in realtime. This needs websockets and a push service.

The easiest way is to use Laravel WebSockets. There is a very convincing demo here : 
https://github.com/beyondcode/laravel-websockets-demo

I'd like to keep the existing discussion framework and ui, but make it real time :-) Easier to say than build

**Comment by philippejadin** [comment]
Beside using websockets and increasing the hosting complexity, there is also the option of doing polling. Unpoly has a nice example : 
https://github.com/unpoly/unpoly/issues/63

Polling uses server resources... it would be nice to have adaptive polling time, depending on the time we received an event (if it's 2 hours ago, no need to poll every 5 seconds).

**Comment by danielsum** [comment]
Hi @philippejadin, I've integrated the  Laravel Websockets.

I think we can make a run installer to simplify the use of Laravel Websockets, if there is no websocket we can make a kind of fallback to make a polling every X seconds (depending on configuration.

What do you think ?

**Comment by philippejadin** [comment]
this would be even better! maybe the js frontend can do this job

anyway I trust you 110% to find a great solution :-)
