### ISSUE TITLE
Add button to return to top in conversations

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#246]
An arrow that appears scrolling on a full screen height, that stays in the bottom right, that basically goes to top.

or some navigation system like discourse and flarum

or colapsable comments.. : #193

**Comment by danielsum** [comment]
@philippejadin => this as been done on local ? any preference for the icon image ? For now it will look like this : 

https://www.evernote.com/l/AHdSThaKIG1MbIKFqgKun12Rvv7EaL4_kx4

**Comment by danielsum** [comment]
@philippejadin => I've made a pull request : https://github.com/philippejadin/agorakit/pull/248

You can close it if it's ok => don't forget to recompile app.js as it will have a conflict
