### ISSUE TITLE
conversation en MP

### ISSUE THREAD

**Issue by PierreLecomte** [agorakit/agorakit#274]
J'ai remarqué qu'il n'y avait pas d'historique des conversations privées, ce qui est un peu dommage.
Ce n'est pas un point bloquant, mais ça serait un plus !

**Comment by philippejadin** [comment]
Je décide de ne pas implanter cette fonctionalité et de rediriger les personnes vers le mail.
Par contre cela nécessite ceci : https://github.com/agorakit/agorakit/issues/285
