### ISSUE TITLE
Wiki for each group

### ISSUE THREAD

**Issue by miloskroulik** [agorakit/agorakit#279]
It would be great if each group could have a wiki tab, which would allow to create a tree of wiki pages with navigation sidebar. It should allow using files that are uploaded to the group and referencing event and discussions.

**Comment by philippejadin** [comment]
This is a great idea of course! Problem is lack of development time on my side to make it happen. If you or anyone else wants to work on it, I'm more than happy to provide guidance and help.

**Comment by miloskroulik** [comment]
Thanks, I would like to do that, but I'm not sure, if I will be able to work on that anytime soon.
