### ISSUE TITLE
No access to HTML source code

### ISSUE THREAD

**Issue by nleguillarme** [agorakit/agorakit#297]
Hi.

We just found out that we have no more access to the HTML source code when writing new comments. We used this functionality quite often, for instance to resize images, etc.

**Comment by philippejadin** [comment]
It's a "feature" of the new ckeditor. They recommend to add all the needed features people do in code using the UI. This means we should list what is needed and missing : 

- tables
- image resize
- something else?

**Comment by philippejadin** [comment]
tables are back (not filtered anymore)
