### ISSUE TITLE
Chat system

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#298]
Some users mentioned they'd like to have a chat system inside agorakit.
I don't want to reinvent the wheel and would like to integrate an existing solution 

Here are my ideal requirements 
- open source
- available public server
- easy to integrate on the client side (moderately complex js)
- allow to merge users / create users on the fly from existing agorakit users
- has a nice android/iphone client to access
- provide chat history when you reconnect (irc doesn't for instance)
- is somehow widely used
- has a future

Anyone has an idea / comments?

On my list are :
- matrix/riot
- xmmp
- rocket.chat
- irc (yes I know)

**Comment by petrk94** [comment]
@philippejadin XMPP is solid, but old and much heavy, but there are many public server around the world (trust question?), for selfhosting snikket https://snikket.org/ would maybe the easiest solution to run.
Matrix is raising and seems logically for usage.
Rocketchat has to be selfhosted too, make the whole thing more complicated, but admin can better handle hate message or user blocking etc.
IRC, well, I dont know it much, so its easy to integrate a server whos already online, but running a own server make it complicated.

**Comment by philippejadin** [comment]
and thenI found this, that seems VERY interesting as well : 
https://zulipchat.com/for/working-groups-and-communities/

**Comment by boherm** [comment]
Hi !
@philippejadin As we have to use a sort of websocket server to make a chat system with Agorakit users and groups, why don't use Laravel echo with redis instead of a third party app ?

It can be packaged easily and integrated properly into Agorakit ui.
If administrators can't use this functionality with their production environment, we can put a flag to disable this feature and let them set a link to a third party app of their choice, for instance.

The idea behind this is to give us the opportunity to gradually expand this chat system and some add cool features like allowing quick links to topics or files.

**Comment by philippejadin** [comment]
@boherm I'd love to do it that way, but I have no experience developing this. Would like to contribute?

I'm really pondering all options.

What I'd like to introduce, if we go the laravel / echo / builtin way, is to allow to "enhance" a discussion by turning it into a quick chat. It would work the same as the current discussion system, but it would be realtime.

Also, some users ask for an app for their phone, a pwa could handle that, but then there is the problem of notifications, etc... a bit over my head I'm affraid (I'm more a DB and backend guy than a JS dev)

**Comment by boherm** [comment]
@philippejadin With pleasure ! :-)

If I understand you well, and if we go for the laravel echo way, you want to transform the current discussion system into a realtime one ?

In one older project that I worked for, we used Google Firebase Cloud Messaging (FCM) but I always hated to be dependant of an external service and Google to do same web notifications.

**Comment by philippejadin** [comment]
@boherm great news!

I'm trying to find a way to help those users who asked a "chat feature" in Agorakit. As I understand it, they want quicker interactions. For instance, without a chat system, part of the discussions move to whatsapp or any other instant messaging solution and so the content is lost for others.

I don't think it's a good idea to have a separate chat module for each group, because in this case the users will always have to choose between "discussion" and "chat". So my idea is to allow realtime commenting in the existing discussions. 

As for the implementation, it seems laravel ecosystem often uses pusher (which offers a nice free plan and is hassle free). Might be nice to it with pusher first, and maybe provide alternatives like this: https://github.com/beyondcode/laravel-websockets for not too hard hosting and also to have multiple drivers available.

And later work on providing a better experience on smartphones with notifications.

(ps : je suis francophone au cas où :-) )

**Comment by boherm** [comment]
@philippejadin Ok I see !
I totally agree with you ! :)

I think that the easy way is to simply improve discussion system already here and add in it new replies in real-time, with reactions (like I saw in older issue), and so on.
Its certainly better for UX and for users understanding !

Laravel Websockets can be a good alternative ! :)

(ps : Ahah oui je sais, mais pour nos amis parlant anglais c'est toujours mieux d'avoir une langue commune !)

**Comment by boherm** [comment]
By the way, for futur mobile app notifications, we can use free plan of https://onesignal.com/ and invite admins to subscribe on it for their self-hosted Agorakit version :)

**Comment by philippejadin** [comment]
This is very exciting! I'm also looking at pwa stuff, which might be very useful as well.

**Comment by boherm** [comment]
> This is very exciting! I'm also looking at pwa stuff, which might be very useful as well.

For applications, I think you should look also at Flutter (https://flutter.dev/). With this system you can develop cross-platform native apps easily and more powerfull than pwa!

(I always wanted to make some good stuff with this technology! :-D)

**Comment by philippejadin** [comment]
Note also that the current code, uses simple polling to reload the comments, and there is also a specific route for that, that returns only the comments newer than the last one shown when the page was loaded. But it doesn't work perfectly and might probably be too taxing on the server (or not?)

**Comment by philippejadin** [comment]
I'm currently watching livewire screencasts, and it's quite excitingfor an semi amateur dev backend guy like me :-)
There is the option of using echo as well with it. But it would probably mean dropping unpoly which is so easy to add super quick responses. Or maybe integrate the two, or switch to turbolinks as they recommend in livewire docs...

Questions questions, and later, choices! Advices always welcome. I'd like to keep it as simple as possible, keep the stack small, and keep the barrier of contribution not too high (including for me hehe)
