### ISSUE TITLE
Mapbox maps not showing anymore

### ISSUE THREAD

**Issue by quenenni** [agorakit/agorakit#308]
From the browser Network console, I see lots of response 410 from mapbox.
It's for all the links like this one:
```
https://a.tiles.mapbox.com/v4/mapbox.streets/14/893/5495.png?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
Following the link, you reach a page with this message:
```
Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"
```
And on the page https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4, you can read:
> ... We’ll be slowly rolling out this deprecation to give users time to migrate their map styles and chat with our team. On March 31st, you’ll no longer be able to create new Classic map styles or update existing Classic styles via the Uploads API and Mapbox Studio. Then on June 1st, we will no longer support requests to our Legacy Maps and Legacy Static Images APIs from new applications and websites...

**Comment by philippejadin** [comment]
It means it's time to revert to leaflet (which is completely free), but it's a lot of work basically I need to redo all the js. (and I don't like javascript :-) )

**Comment by philippejadin** [comment]
I didn't notice it earlier because my mapbox api token still works for now
(created earlier). I'll fix this (help welcome as always :-) )
--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org

**Comment by philippejadin** [comment]
note to self : here is an implementation to take ideas from : https://github.com/nafiesl/laravel-leaflet-example/blob/master/resources/views/outlets/map.blade.php

**Comment by philippejadin** [comment]
just an update : there is leaflet branch on the repository that is **almost** working so this issue will be solved sooner or later. Basically no more dependencies on mapbox

**Comment by philippejadin** [comment]
This was really painful but it works now using pure leaflet. Closing this one (for good?)

**Comment by quenenni** [comment]
Great.
Thanks a lot for this. Mucho appreciated.

I'm a bit overwhelmed by other stuffs atm, but as soon as I have some free time, I'll test that.
