### ISSUE TITLE
external links / services used

### ISSUE THREAD

**Issue by quenenni** [agorakit/agorakit#309]
In a less technical and more political thinking.. we have hesitations with the external libraries AgoraKit is using.

Currently, Agorakit is using:
- fontawesome.com
- jsdelivr.net
- storage.googleapis.com
- mapbox (if you use the map feature)

We are very careful with the applications we offer.
We are very strict on the subject of user privacy.
It means no applications / services we offer have any link to any google subservices or others from the GAFAM and co.

- Jsdelivr.net is using google analytics tool (https://github.com/jsdelivr/jsdelivr/blob/master/Privacy%20Policy%20-%20jsdelivr.com.md#analytics)
- There is a call to storage.googleapis.com, I'm not sure why. I can block it, nothing changes in the app (nothing stops working)<br />
- In order to use fontawesome, Agora calls netdna-cdn.com.
From they linkedin account, we can read "NetDNA has developed its own data centers with proprietary software that lets the company provide .. blah blah blah."
- And about fontawesome.com, it's really not clear what they collect and what they do with the data.<btr />
https://fontawesome.com/privacy 
  -> Does Font Awesome share data about me with others? 
  "The companies behind those services may collect data about you on their own, for their own purposes. Some of these services may be used to collect information about your online activities across different websites. All of these services are based in the United States."

I know you can use Firefox add-on like Decentraleyes, but I personnally think we shouldn't use them as by using them, you legitimate all the craps from thoses companies.
For few millions computer aficionado, it's easy to protect themselves, but that means above all that billions of people won't be protected.

So, my question would be.. 
Do you think it would be possible to have all these features (external links / libraries) optionals in a not too far future release?

**Comment by philippejadin** [comment]
I just moved the issue, thank you for the detailed report! I'll reproduce the steps I can in the future for a next release

**Comment by philippejadin** [comment]
No more dependencies on fontawesome (self hosted now), mapbox not needed anymore

I think it's "good enough" for now

**Comment by quenenni** [comment]
I finally took the time to update my agorakit instance and all seems to work perfectly.

No more of these dependancies.
Map is working well.
Statistics also works nicely.

This is beautiful.
Big thanks
