### ISSUE TITLE
Toggle ability for users to edit any discussion?

### ISSUE THREAD

**Issue by ali1933oth** [agorakit/agorakit#314]
Many users seem confused by the default behavior of being able to edit any OP post of a thread. I've seen a few times that a user will overwrite the OP instead of making a new reply.

I understand its value, as you can make collaborative edits on a post, as in a wiki.

Can this be toggled? Or perhaps a checkbox to allow the user to decide if they want to make a collaborative wiki thread or a traditional thread?

**Comment by philippejadin** [comment]
Could be done, would you like to work on it?

On Monday, August 3, 2020, ali1933oth <notifications@github.com> wrote:
> Many users seem confused by the default behavior of being able to edit
any post. I've seen a few times that a user will overwrite the OP instead
of making a new reply.
>
> I understand its value, as you can make collaborative edits on a post, as
in a wiki.
>
> Can this be toggled? Or perhaps a checkbox to allow the user to decide if
they want to make a collaborative wiki thread or a traditional thread?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci6.googleusercontent.com/proxy/HhGlYqIT7eU4NQ6wN1kP7AdubnvqPFpFhyVxTo3xJNlihujDQtSCvIqsQk5XNh6ktkgm9o7ySwa8MYFkNojpaI54KzE-I-S8tMOAKHECrMf4crOf2mJRsy48SJho32re2dyJcClqQ9i9mw8nmiivIQnEkroM59F9MmB8i7HBLdyYj17bmteUQJVXiTtTVHyDZmeW27uLHe3YOjxss-nxbu7PtyI=s0-d-e1-ft#https://github.com/notifications/beacon/AAJEZ5OLF2F5VGKGI5AJIC3R63D3RA5CNFSM4PTM7JFKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4KAPZ46A.gif
>

-- 
--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org
