### ISSUE TITLE
[documentation] explain cron job install

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#328]

**Comment by BdM5959** [comment]
Hi Philippe,
I installed your web solution (agorakit) on mutual server.
System works well, just I would like forward notifications.
I suppose It's based on a cron task running daily a php script, 
could you provide me information for implementing it.
Thanks
Bruno

**Comment by philippejadin** [comment]
what do you mean with forward notifications?
--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org

**Comment by BdM5959** [comment]
Hi Philippe,
when user has set into group user preferences a notification timing.
--------------
e.g.
Q: How often do you want to receive notifications by email?
A: daily
-------------

At this time user doesn't receive anything from server, so something isn't set correctly on my shared server
Thanks
Bruno

**Comment by philippejadin** [comment]
You need to setup a cron job as explained here : https://laravel.com/docs/8.x/scheduling#starting-the-scheduler

**Comment by BdM5959** [comment]
ok,
I'm going to do that
Thanks
Bruno

**Comment by BdM5959** [comment]
Works perfectly
Thanks for support
