### ISSUE TITLE
Installation / configuration issue : can't register after install

### ISSUE THREAD

**Issue by manu-p** [agorakit/agorakit#335]
Hi, thanks for this project, sounds good!

Just followed the [Quick start](https://docs.agorakit.org/#/en/install) installation guide to give it a look on my server (Ubuntu 18.04 / Apache 2.4 / PHP 7.4 / MySQL 5.7), and while I've been able so far to get access to my https://agora.mydomain.me, I'm remaining stuck here.

I mean, I get a front page with menus and a page showing:

> **Agorakit
> Error sit nihil qui animi.**
> blabla
> 

But when I click in Connection or Register, I just get:

> Not Found
> 
> The requested URL was not found on this server.
> Apache/2.4.46 (Ubuntu) Server at agora.mydomain.me Port 443

The URL is https://agora.mydomain.me/login (or register).

The whole PHP and conf files are stored under /var/www/agorakit and owned by www-data.

The apache2 conf file starts with:
```
<VirtualHost *:443>
	ServerName agora.mydomain.me

      	DocumentRoot /var/www/agorakit/public/

        <Directory /var/www/agorakit/public/>
              Options Indexes FollowSymLinks MultiViews 
              AllowOverride None 
              Order allow,deny 
              allow from all 
      	</Directory>
etc.
```
The  .env file starts with:
```
################# Agorakit configuration file #################

APP_ENV=production

# Turn on or off debug. Use false on a production server, this is a security measure!
APP_DEBUG=false

# This key will be generated by laravel using php artisan key:generate
APP_KEY=base64:trji3h/MaNyleTTersANDnuMbers=

# The name of your application, used in various places like titles, email subjetc, etc...
APP_NAME='Agorakit'

APP_URL=https://agora.mydomain.me

APP_LOG=daily

# Default locale to use if not detected. Use two characters locale identifier
APP_DEFAULT_LOCALE=fr

# Database credentials
DB_HOST=localhost
DB_DATABASE=agora
DB_USERNAME=root
DB_PASSWORD='theVeryComplexMySQLPassword'
```

What's wrong with it, doc?

**Comment by philippejadin** [comment]
Could be AllowOverride None in apache ?
As I understand it you need to allow htaccess overriding apache params for url rewriting. I'm really not an expert at server ops, but this will probably help you debug the issue.

Keep us informed of your results :-))

**Comment by philippejadin** [comment]
you could also try to visit https://agora.mydomain.me/index.php/login and see what it returns. If it works it means you have url rewriting disabled

**Comment by philippejadin** [comment]
here : https://stackoverflow.com/questions/28242495/laravel-the-requested-url-was-not-found-on-this-server

**Comment by manu-p** [comment]
That was it, thanks @philippejadin!

Now that it works fine, I realize I populated the database (alright it was written in the so Quick start guide...) when I did:
`php artisan db:seed`

And now, I can see in the 'users' table there's already an Administrator account (which I never, ever, name like this, cause it's too an easy id to try for hackers). But anyway, do I have to try and find its password? Or is there someone to tell the password that was set for this account?

Because when I got to the register popup and tried to add a new account, I got to a page saying:

> A fatal error occured
> 
> Expected response code 220 but got an empty response
> 
> Contact the server admin to get help and explain what you were trying to do. Provide this error message to help fix the bug.

I feel like I'm just almost in touch something interesting (hopefully), but looking like a closing door so far. :-/

**Comment by philippejadin** [comment]
- the DB seed is only used for development, it creates dummy data so I can check the UI in a consistent way (I should add it to the doc :-)). You might want to simply delete and recreate the DB and just migrate without seeding.
- the administrator password is 123456789 isn't it nicely secure? :-)

If you don't seed the DB, the first user account you create will have super admin rights, that's the recommended way to do it in production.

The latest code 220 error you get is most probably because you need to configure a way to send emails

All this makes me thing the doc could be improved. If you want and have time, you can submit pull requests with better doc in the docs directory. Help highly welcome ! Especially from someone trying to install for the first time.

**Comment by manu-p** [comment]
Yes! One more step to the light! ;-)

Just dropped the database, recreated it and "migrated" it, and then I could setup a new account (still with this mail related 220 error), but now when I try to log in I get something more acceptable telling me I did not verify the email address associated with this new account. Sure! I didn't receive the mail... (because it didn't exited the server, I guess).

Now, here's what the "Mail server settings" look like in my .env file:
```
MAIL_DRIVER=mail
MAIL_HOST=mail.gandi.net
MAIL_PORT=465
MAIL_USERNAME=<my mail address>
MAIL_PASSWORD=<the related password, enclosed with quotes since it holds some special chars such as ! and %>
MAIL_ENCRYPTION=SSL/TLS
```
I know it's working fine, these are the SMTP params I'm getting from my mailer (thunderbird). I also tried to enclose all these params with quotes ( ' ) for nothing better.

And here's what the doc says about this section:

```
    MAIL_DRIVER=mail // driver to use for sending emails. Use mail to use php built-in mail function
    MAIL_HOST=mailtrap.io // hostname if you use smtp for sending mails
    MAIL_PORT=2525 // port if you use smtp for sending mails
    MAIL_USERNAME=null // login if you use smtp for sending mails
    MAIL_PASSWORD=null // password if you use smtp for sending mails
    MAIL_ENCRYPTION=null // encryption if you use smtp for sending mails
```

I guess there's something wrong with my params, but which one(s)?

(I could force the "users" table verified field, but that wont help to send mails from agorakit...)

**Comment by philippejadin** [comment]
change 

`MAIL_DRIVER=mail`

to

`MAIL_DRIVER=smtp`

So confusing isn't it? :-/

**Comment by manu-p** [comment]
Yep, it is! Some comments missing to auto-document the .env file maybe. 

So here's what the .env Mail server settings looks like now:
```
MAIL_DRIVER=smtp
MAIL_HOST=mail.gandi.net
MAIL_PORT=465
MAIL_USERNAME=<my mail address>
MAIL_PASSWORD=<the related password, enclosed with quotes since it holds some special chars such as ! and %>
MAIL_ENCRYPTION=SSL
```
Note I had to reduce the mail encryption to SSL only, no other try ('SSL/TLS' nor TLS) did the trick.

And guess what? It works!

Thanks for taking time on a sunday, @philippejadin, to help me finish this installation.
