### ISSUE TITLE
Default display All groups in home page

### ISSUE THREAD

**Issue by manu-p** [agorakit/agorakit#336]
Hi, maybe that's normal, maybe not... 

When I log in, I have to select Groups > My Groups (or Overview > All groups) to see them displayed. Or else, it's just the text I setup in the "Home page presentation text <em>for logged-in users</em>" settings section.

I'd wish users to see their groups when just logged in, without the need to click somewhere to get them displayed.

Any setting somewhere to get https://domain/groups as home page for users?

**Comment by philippejadin** [comment]
The homepage is curently empy if you are not the member of any group or have no discussions to see in the groups you are member of. It should show a nice visual to motivate the user to join at least one group. The group list is not intended to be a home page, the homepage as I see it is more like a dashboard.

Makes sense?
