### ISSUE TITLE
Groups browsable without login

### ISSUE THREAD

**Issue by manu-p** [agorakit/agorakit#338]
No need to connect to see groups, even private groups: when on the login/register page just click in **Overview** > **All groups** to see them, and see what's in their discussions, calendars, files, etc.

This is not possible when the "Embed this page" has been clicked before, since there's no header anymore.

Login just adds the ability to participate. 

It's blocking for what we want to set up. Unregistered people should not get access to groups lists and contents.

**Comment by philippejadin** [comment]
You only get access to the group description, not the group content, this works as intended
