### ISSUE TITLE
Default end date value when creating new event

### ISSUE THREAD

**Issue by teraservices** [agorakit/agorakit#339]
When creating a new event by clicking on the date while in grid/month view, the end date is defaulted to next day but should be same day.

**Comment by philippejadin** [comment]
Probably an error on the server setup at least here it works. Closing for now

**Comment by teraservices** [comment]
![ajouter un evenement agenda2](https://user-images.githubusercontent.com/24590352/99584897-de5fc500-29e5-11eb-8c97-6dc219b2f4d7.gif)
Hello Philippe,
The problem is the same on your server. It only occurs when clicking in a day to add the event. look at the gif attached.

**Comment by philippejadin** [comment]
now I understand :-) will check that

**Comment by philippejadin** [comment]
This is finnaly solved in latest release. Need some more testing.
