### ISSUE TITLE
Grid view displays events in the wrong time zone

### ISSUE THREAD

**Issue by gszathmari** [agorakit/agorakit#341]
When I add new events in list view (https://example.com/groups/1/actions?type=list), the events show up in the wrong time zone under grid view (https://example.com/groups/1/actions?type=grid).

My time zone is AEST, so if I create an event starting at 3 pm on a Saturday, the Grid view says the event starts at 1 am on Sunday.

**Comment by gszathmari** [comment]
[This line](https://github.com/agorakit/agorakit/blob/master/config/app.php#L67) should be changed from

`'timezone' => 'Europe/Brussels',`

to

`'timezone' => env('TIME_ZONE', 'Europe/Brussels'),`

**Comment by philippejadin** [comment]
Thank you for reporting. This is changed in the latest commit.
If you see other problems with timezone, let me know.

**Comment by GaborEH** [comment]
Thank you
