### ISSUE TITLE
/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(326):

### ISSUE THREAD

**Issue by robensy** [agorakit/agorakit#360]
Ciao sto ricevendo questo errore...

/home/host1828396/mydomain.com/htdocs/www/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(326): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionContent(Object(TypeError))
#3 /home/host1828396/mydomain.com/htdocs/www/vendor/laravel/framework/ at /home/host1828396/mydomain.com/htdocs/www/vendor/symfony/error-handler/ErrorRenderer/HtmlErrorRenderer.php:49)
[stacktrace]
#0 {main}
"}

**Comment by philippejadin** [comment]
without the complete error message it's hard to know what's going on

**Comment by robensy** [comment]
hello you or sent the log file, thanks for your patience.
[laravel.log](https://github.com/agorakit/agorakit/files/6223718/laravel.log)
