### ISSUE TITLE
allow to recover soft deleted user accounts in admin panel

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#390]

**Comment by ihtishamKhan** [comment]
Why admin is not able to see all the users? I am currently seeing admin there in members menu

**Comment by philippejadin** [comment]
are you looking at this route : http://localhost/admin/user ?

The idea would be to show the soft deleted users in this table, and add a button to undelete the users there. I think the best way would be to change the edit button to a "undelete" button for softdeleted users.

Thank you for your interest in the project! I'm here to help if you need any assistance :)

**Comment by philippejadin** [comment]
This is indeed fixed, thank to #459
