### ISSUE TITLE
Error when migrating from 1.7 to 1.9

### ISSUE THREAD

**Issue by VMFnet** [agorakit/agorakit#397]
Hello, when upgrading a previous install which was at version 1.7 to the latest 1.9 today (manual update method, i didn't have the update script yet), i encountered this issue when runnning the migration step : 
$ php artisan migrate 
Migrating: 2021_04_23_134040_update_charset
   Illuminate\Database\QueryException 
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4)
  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:685
    681▕         // If an exception occurs when attempting to run a query, we'll format the error
    682▕         // message to include the bindings with SQL, which will make this exception a
    683▕         // lot more helpful to the developer instead of just the database's errors.
    684▕         catch (Exception $e) {
  ➜ 685▕             throw new QueryException(
    686▕                 $query, $this->prepareBindings($bindings), $e
    687▕             );
    688▕         }
    689▕ 

      +7 vendor frames 
  8   database/migrations/2021_04_23_134040_update_charset.php:20
      Illuminate\Support\Facades\Facade::__callStatic("unprepared")

      +21 vendor frames 
  30  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

Do you have an idea what went wrong here and maybe a fix to this problem ?

Thanks !

**Comment by philippejadin** [comment]
I already got this problem. I think it's related to mysql version. It should be 5.7 or later, can you check ?

**Comment by VMFnet** [comment]
yes, you're absolutely right, we're using 5.5 currently.  
I'll check if the mysql version can be upgraded on that specific server.
