### ISSUE TITLE
Youtube video not showing up

### ISSUE THREAD

**Issue by fodevaux** [agorakit/agorakit#402]
This discussion has a youtube video integrated, that does not show
https://forum.budgetparticipatifnamur.be/groups/4/discussions/34

However, when editing the page, everything seems fine

![image](https://user-images.githubusercontent.com/10889235/144022869-db17415e-09b2-4533-bc6f-965b702f2a34.png)

**Comment by philippejadin** [comment]
I putted the link after the f: embed and it works, but it's a hack. I need to check the html text handling code and enhance it :-)

**Comment by fodevaux** [comment]
Sorry, I wasn't able to reproduce the hack neither. I tried it here https://forum.budgetparticipatifnamur.be/groups/4/discussions/36
