### ISSUE TITLE
Images in emails not showing up

### ISSUE THREAD

**Issue by fodevaux** [agorakit/agorakit#403]
In emails opened on Gmail, some thumbnail images do not show up
![image](https://user-images.githubusercontent.com/10889235/144228835-859f38fa-8d46-46f8-84f5-03b5e3a5d314.png)

Example of thumbnail not showing up
https://forum.budgetparticipatifnamur.be/groups/4/files/14/thumbnail
which leads to https://forum.budgetparticipatifnamur.be/images/extensions/pdf.svg

I believe Gmail doesn't do the redirection of thumbnails

**Comment by philippejadin** [comment]
Thank you for the detailed report. I'll see if I can avoid the redirect. It's the only solution since gmail has a system to anonymize images and it probably does not support redirect as you said :-)
