### ISSUE TITLE
Handle correctly duplicate users (same email) on registration

### ISSUE THREAD

**Issue by fanzila** [agorakit/agorakit#416]
Iaorana, 

Impossible to register an user.

You can test it here : https://diapason17.org/
It is currently in debug mode.

To reproduce, click on register, fill up user & email then password click register and then the popup disappear with no redirect to the signup confirmation page and not being logged.
The user is not inserted in the database but the email is sent.
The email confirmation link redirect to a 404 page (ex: https://diapason17.org/confirm/KUk7yTkSxEnQQezW7tH8J24IknCK33 )

I have another Agorakit on the same machine/php/apache/MariaDB https://rivalame.fr/ which is working fine.
Any ideas ?

### Infos
Agorakit master branch up to date sept 9, 2022
Php 8.1.9
10.3.34-MariaDB-0+deb10u1 Debian 10
No errors in apache/php logs 

Thanks!

**Comment by fanzila** [comment]
It happen when the email is already known, it should be classified as a bug

**Comment by philippejadin** [comment]
This is indeed a bug that must be adressed, re-opening and re-titling
