### ISSUE TITLE
problem with the app update

### ISSUE THREAD

**Issue by quenenni** [agorakit/agorakit#428]
I updated my instance to last commit (from this commit 9ecf01da5ed4c105b3bbb484c980607667375c5a).

I followed the update procedure
```
    $ php artisan down
    $ git pull
    $ composer install
    $ php artisan migrate
    $ php artisan up
```

Unfortunately, now I'm having this error when entering a group (and other pages);
```
Class 'Purifier' not found (View: /var/www/agorakit/resources/views/users/show.blade.php) 
```

**Comment by quenenni** [comment]
Sorry for the delay.
I tried `sudo -u www-data composer update` but got an error:
```
mmap() failed: [12] Cannot allocate memory                                                                                                                     
                                                                                                                                                               
mmap() failed: [12] Cannot allocate memory                                                                                                                     
                                                                                                                                                               
mmap() failed: [12] Cannot allocate memory                                                                                                                     
PHP Fatal error:  Out of memory (allocated 1648898048) (tried to allocate 67108872 bytes) in /usr/share/php/Composer/DependencyResolver/RuleSet.php on line 83 
                                                                                                                                                               
Fatal error: Out of memory (allocated 1648898048) (tried to allocate 67108872 bytes) in /usr/share/php/Composer/DependencyResolver/RuleSet.php on line 83
```
I changed the memory_limit of my php up to 1.6Go, but still the same error. (my vps has 2Go Ram and that sould be fine for a web app)

I then tried `sudo -u www-data php -d memory_limit=-1 'which composer' update` to give max memory, the process froze the server for 15 min before I was able to kill it.

I deleted the vendor folder and tried again (as Iread on forums talking about that problem). Again the process froze completely the server and after 10 min, the process exit with the same memory error.

So I'm back at the beginning.
What can I do?

Thanks.

Nb:
I also have the msg `Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/`
The link told me to do a `sudo -u www-data composer self-update --2`, but got an error:
```
  Command "self-update" is not defined.
```

**Comment by philippejadin** [comment]
I would try with a fresh install of composer 2. Report here if it doesn't
not solve the problem.

Good luck!
