### ISSUE TITLE
ical error

### ISSUE THREAD

**Issue by quenenni** [agorakit/agorakit#429]
After my failed update (https://github.com/agorakit/agorakit/issues/428), I went back to my backup version.

I wanted to update because I have a problem with ical on this version, hoping it could be fixed on last commit.

When going to action page in a group, when clicking on either of the 2 buttons at the bottom "Lien ical public pour ce groupe" or "Lien ical personnel", I have a fatal error:
```
Class 'Spatie\IcalendarGenerator\Components\Calendar' not found 
```

**Comment by philippejadin** [comment]
seems solved
