### ISSUE TITLE
Cannot reset database

### ISSUE THREAD

**Issue by Anonymous941** [agorakit/agorakit#436]
I somehow ended up in a state where I have no accounts and can't make a new one because it's disabled.  I'm trying to reset my database and have deleted the MySQL database many times, reset all of the files, ran many different `php artisan` commands, but it just won't reset my database.

**Comment by philippejadin** [comment]
You can empty the users table, then register a new user. The first registered user is admin.

Or delete and recreate the DB, then run `php artisan migrate`

Either should work

**Comment by Anonymous941** [comment]
@philippejadin I finally got it when I cleared the cache, but thanks for your help...

**Comment by philippejadin** [comment]
I'm happy you found a solution. Clearing the cache is something I often forget...
