### ISSUE TITLE
is there any installation guide ?

### ISSUE THREAD

**Issue by mamyn0va** [agorakit/agorakit#438]
Hi!

First, thanks for this wonderful tool, it's perfect for the needs of little associations.
I was looking for an installation guide, a Dockerfile or even better, a docker-compose but I didn't find anything on the github repo and the readthedocs seems to be empty.
Could you please provide some basic instructions to install agorakit on a VM and I would be happy to provide a Dockerfile and a docker-compose file ?

Thanks a lot !

**Comment by philippejadin** [comment]
Hello, thank you for the proposal! When I started working on agorakit I didn't know docker. I'd love to have a working docker setup, so your help would be greatly appreciated.

Here are some basic install docs : https://github.com/agorakit/agorakit/blob/master/docs/en/install.md

As I understand it, Laravel provide sail, a docker based tool for dev, which might be an interesting start ? (or not) : https://laravel.com/docs/10.x/sail

Merci :-)

**Comment by mamyn0va** [comment]
Thanks !
