### ISSUE TITLE
add cover to actions

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#442]
Work is in progress in the "cover" branch.
Create a hasCover trait that can be applied to actions.
Update the edit and show views for relevant models (here, actions)

A cover is simply an image file located in /storage/[model type]/[model id]/cover.jpg

The image can be uploaded trough the edit form.

**Comment by ihtishamKhan** [comment]
Can you please provide description for it

**Comment by philippejadin** [comment]
Just added some background info. You can check the cover branch.
But, it's probably better to let me finish this feature since it's almost completed in the cover branch
