### ISSUE TITLE
Error on click on discussion since migration

### ISSUE THREAD

**Issue by Adeline-44** [agorakit/agorakit#452]
I've made a migration to 1.7 and since, when I go into a group discussion I've got this message

foreach() argument must be of type array|object, null given (View: /var/www/agorakit/resources/views/reactions/reactions.blade.php) {"view":{"view":"/var/www/agorakit/resources/views/reactions/reactions.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-905407829 data-indent-pad=\" \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1558</a><samp data-depth=1 class=sf-dump-expanded> 

It is the same for downloading a file :

Sorry, the page you are looking for could not be found.

File not found in storage at groups/2/files/filename.pptx

**Comment by Adeline-44** [comment]
yes

**Comment by philippejadin** [comment]
Did you run the update script?

**Comment by Adeline-44** [comment]
yes

**Comment by philippejadin** [comment]
Do you know what caused the problem?
