### ISSUE TITLE
Download file error - version 1.9

### ISSUE THREAD

**Issue by Adeline-44** [agorakit/agorakit#453]
Since, migration, I always get the message
Sorry, the page you are looking for could not be found.
File not found in storage at groups/4/files/filename.pdf

Php version 8.2
Migration steps :
php artisan down
composer install
php artisan migrate
php artisan up
php artisan config:cache
php artisan storage:link

It seems that the directory /storage is not the same in version 1.7 to version 1.9
What did I miss ?

**Comment by philippejadin** [comment]
If you upgraded from a very old version (more than 4 years ago) you can run
artisan agorakit:convertfiles but I don't think it's the problem here.

Else you might post relevant log entries

**Comment by Adeline-44** [comment]
When I make php artisan agorakit:convertfiles ; I have the message "file not found" follow by the name of the file.

**Comment by philippejadin** [comment]
Is the install publicly accessible? Could you send me access privately? Are
the files present in storage/app/groups?

Hope you'll manage to fix the issue 🙂

**Comment by Adeline-44** [comment]
I came back to a backup version 1.7
I got the same error. The access right are ok.
I don't have any groups directory, I only have users...

**Comment by philippejadin** [comment]
Can you upload a new file in a group and check if the file appears in the
storage directory?

If the file appears and you have no other files in the same place, it might
means the file were deleted somehow. Maybe a wrong way to manage the git
updates?
Maybe also check your backups. I never had any issues with file
disappearing like that so it's really hard to tell what happened.

Hope that helps,


--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org

**Comment by Adeline-44** [comment]
Yes I think you're right. I should have miss something or make a bad git command.
So we can close this issue.
Thank you for your support
