### ISSUE TITLE
Error when adding an event on agenda

### ISSUE THREAD

**Issue by Adeline-44** [agorakit/agorakit#456]
I've got this error when I try to add an event on the agenda.
![image](https://github.com/agorakit/agorakit/assets/76005387/bc1515dd-0b09-4381-abaa-bbae8edc4133)

My version is 1.9

**Comment by philippejadin** [comment]
did you run the latest migrations ?
--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org

**Comment by Adeline-44** [comment]
I've tried, but...
![image](https://github.com/agorakit/agorakit/assets/76005387/db06c20b-48d2-4290-baa2-071f26e4d8e9)
