### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by kMikaZu** [agorakit/agorakit#458]
Is this project still maintained?

**Comment by philippejadin** [comment]
Yes, and there are quite a lot of new stuff on the roadmap. I still need to
write it all down for sharing.

Le sam. 6 avr. 2024, 20:16, Mikaël Janssens ***@***.***> a
écrit :

**Comment by philippejadin** [comment]
If there is anything you'd like in terms of new features or bug fixes, you are more than welcome to write it here (for bugs), or on the feature vote system here : https://feedback.agorakit.org/
Ot of course in the Agorakit users group here : https://app.agorakit.org/groups/39

**Comment by philippejadin** [comment]
I will close this issue, since I think I answered it. The main branch has all the work done in the last year. Starting from now, I will make proper branches to make it clear what I (and others) are working on.
