### ISSUE TITLE
Undefined variable $group

### ISSUE THREAD

**Issue by fabadja** [agorakit/agorakit#462]
Everything is in the title ;-)

PHP 8.2.18
Agorakit 1.9
Laravel version 8.83.27

an error message appears when I follow the following link: https://x.x.x.x/admin/insights

" A fatal error occured
Undefined variable $group (View: /var/www/agorakit/resources/views/group.blade.php)
Contact the server admin to get help and explain what you were trying to do. Provide this error message to help fix the bug."

more details:
"Undefined variable $group (View: /var/www/agorakit/resources/views/group.blade.php) {"view":{"view":"/var/www/agorakit/resources/views/group.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-1164833026 data-indent-pad=\" \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1612</a><samp data-depth=1 class=sf-dump-expanded>"

thanks

**Comment by philippejadin** [comment]
Can you explain what you were doing when the error appeared? Fresh install?

Le lun. 3 juin 2024, 09:51, Fabien Abadja ***@***.***> a
écrit :

**Comment by fabadja** [comment]
it's a fresh install, everything seems to work except this link which returns to the error message given (I created a group)
https://agorakit/admin/insights

**Comment by philippejadin** [comment]
Since it's on a fresh install it will be not too hard to fix I guess.
Thank you for reporting, I'll keep you updated!


--
Philippe Jadin
https://123piano.com
https://fablabke.be
https://agorakit.org

**Comment by linc** [comment]
I had this same issue on a fresh install. I'd run the demo content population, but it was otherwise brand-new. I was logged in as the default admin account.
