### ISSUE TITLE
Add mailing funtionality per group / site wide

### ISSUE THREAD

**Issue by philippejadin** [agorakit/agorakit#51]
- allow group admin to send mailing to group members
- allow super admin to send mailing to all users / to multiple groups

- deduplicate if needed userl ist
- provide some kind of wysiwyg feature
- minimal mail branding if possible
- mail queue ?

**Comment by msjmeyer** [comment]
The allowing of group admin to send to group members would be awesome. 

For that, I would suggest using a site address instead of the admin users email.
