### ISSUE TITLE
Messaging to users ( Feature request)

### ISSUE THREAD

**Issue by msjmeyer** [agorakit/agorakit#80]
For messages to the user, some users might not like it. Giving them the ability would be awesome.

Also for the admin to turn it off globally would be very helpfull for some people.

**Comment by philippejadin** [comment]
Good idea. For implementation (whether it's me or someone else who does it :-) )

- add a checkbox to user profile [x] Show a contact form so others can contact me
- save the status in user->setPreference('accept_contact_form', true|false) (saves as json in the db)
- then check if $user->getPreference('accept_contact_form') to show or not the tab and contact form and message sending in the controller


- add a global setting either in .env (not so pretty) or in the future admin settings page that saves to the settings table already there
