### ISSUE TITLE
Feature request: Ability for admin to create users

### ISSUE THREAD

**Issue by msjmeyer** [agorakit/agorakit#95]
When testing the ability to create and verify users would be a lot of help.

**Comment by philippejadin** [comment]
this can be done in the db easily time being limited I close this. feel free to reopen if urgently needed

**Comment by philippejadin** [comment]
A group admin should be able to invite users by email and in this process it would create new user accounts. Those accounts must be activated by the user himself.

Can you try this workflow and let me know if it works correctly for your use case?
